given_name = input("Given name: ")
family_name = input("Family_name:")
street_address = input("Street address: ")
code = input("City and postal code:")
print(given_name + " " + family_name)
print(street_address)
print(code)